name: spam_detector_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.2.25=hecd8cb5_0
  - libffi=3.4.4=hecd8cb5_1
  - ncurses=6.4=hcec6c5f_0
  - openssl=3.0.16=h184c1cd_0
  - pip=25.0=py310hecd8cb5_0
  - python=3.10.16=hce00570_1
  - readline=8.2=hca72f7f_0
  - setuptools=75.8.0=py310hecd8cb5_0
  - sqlite=3.45.3=h6c40b1e_0
  - tk=8.6.14=h4d00af3_0
  - wheel=0.45.1=py310hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
  - pip:
    - altair==5.5.0
    - appnope==0.1.4
    - asttokens==3.0.0
    - attrs==25.3.0
    - awsebcli==3.25
    - bcrypt==4.3.0
    - blessed==1.22.0
    - blinker==1.9.0
    - botocore==1.40.36
    - cachetools==5.5.2
    - cement==2.10.14
    - certifi==2025.1.31
    - cffi==2.0.0
    - charset-normalizer==3.4.1
    - click==8.1.8
    - colorama==0.4.6
    - comm==0.2.2
    - contourpy==1.3.1
    - cryptography==46.0.1
    - cycler==0.12.1
    - debugpy==1.8.13
    - decorator==5.2.1
    - deprecated==1.2.18
    - exceptiongroup==1.2.2
    - executing==2.2.0
    - fabric==3.2.2
    - flask==3.1.2
    - fonttools==4.57.0
    - gitdb==4.0.12
    - gitpython==3.1.44
    - idna==3.10
    - imbalanced-learn==0.13.0
    - imblearn==0.0
    - invoke==2.2.0
    - ipykernel==6.29.5
    - ipython==8.35.0
    - itsdangerous==2.2.0
    - jedi==0.19.2
    - jinja2==3.1.6
    - jmespath==1.0.1
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - kiwisolver==1.4.8
    - markupsafe==3.0.2
    - matplotlib==3.10.1
    - matplotlib-inline==0.1.7
    - narwhals==1.33.0
    - nest-asyncio==1.6.0
    - nltk==3.9.1
    - numpy==2.2.4
    - packaging==24.2
    - pandas==2.2.3
    - paramiko==4.0.0
    - parso==0.8.4
    - pathspec==0.12.1
    - pexpect==4.9.0
    - pillow==11.1.0
    - platformdirs==4.3.7
    - prompt-toolkit==3.0.50
    - protobuf==5.29.4
    - psutil==7.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyarrow==19.0.1
    - pycparser==2.23
    - pydeck==0.9.1
    - pygments==2.19.1
    - pynacl==1.6.0
    - pyparsing==3.2.3
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.2
    - pyzmq==26.4.0
    - referencing==0.36.2
    - regex==2024.11.6
    - requests==2.32.3
    - rpds-py==0.24.0
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - seaborn==0.13.2
    - semantic-version==2.10.0
    - six==1.17.0
    - sklearn-compat==0.1.3
    - smmap==5.0.2
    - stack-data==0.6.3
    - streamlit==1.44.1
    - tenacity==9.1.2
    - termcolor==2.5.0
    - threadpoolctl==3.6.0
    - toml==0.10.2
    - tornado==6.4.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - typing-extensions==4.15.0
    - tzdata==2025.2
    - urllib3==1.26.20
    - wcwidth==0.2.13
    - werkzeug==3.1.3
    - wordcloud==1.9.4
    - wrapt==1.17.3
prefix: /Users/Rime/anaconda3/envs/spam_detector_env
